# Generated by Django 3.2.4 on 2021-06-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='cnt',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='descriptionsList',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='titleList',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
