# Generated by Django 3.2.4 on 2021-06-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210620_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('due', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='scheduler',
            old_name='descriptionsList',
            new_name='descriptionList',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
