# Generated by Django 3.2.4 on 2021-06-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_job_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('due', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
