# Generated by Django 3.2.4 on 2021-06-21 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postname',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
